# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07616b14e2c9b743ce163c1b4415ee7d4ac4edda8f60ff246ca6b28a06c4182c1f165ccb01403dcf2331d9ddde784e1130b8215cb57e931cc97657f772bc0849

test:
  secret_key_base: 42f7e5d525a5badb096fcc01d0328c95d73430b45c5e7ad5eda2ed20396fbe5898350361416446c2ad76379a819714086eab49668fa352d08a71e19435860e59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
